### ISSUE TITLE
Inconsistent behaviour with Element(s) and manipulation functions

### ISSUE THREAD

**Issue by panec** [strudeljs/strudel#43]
**Describe the bug**
When using Element with selector it is not always clear what will be returned - single item or collection. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Select any `Component` element with multiple child that has class atribute
2. call `this.$element.find('*').attr('class')`
3. Only first class name is returned

**Expected behaviour**
Array with class names is returned for all items in collection. 
Calling `this.$element.find('*').attr('class', 'test')` updates all elements which is expected.

**Desktop:**
 - OS: macOS 10.13
 - Browser: Chrome
 - Version: 67

**Comment by mateuszluczak** [comment]
You are right, `attr` should work as a getter for entire collections the same way as setters. 
It's clearly a bug. Adding labels and prioritising this for 0.8.0.

**Comment by mateuszluczak** [comment]
After having some thoughts about this issue I no longer think it is a bug. 

This API is consistent with how jQuery `attr()` works which in my opinion is a standard for DOM operations (although may have it's lovers and haters)

Every getter in `Element` library works this way, so you will find same behaviour in `data()`, `html()`, `text()`, `prop()` and others, so now the behaviour is consistent. 

`map()` is introduced to handle retrieving the parameters for entire collections of items.

I've found out that your confusion is caused by inaccurate documentation, so I am changing the JSDoc for the attr method and will update the strudeljs.org API docs.
