### ISSUE TITLE
Help Wanted: Can I help?

### ISSUE THREAD

**Issue by birdyboy18** [strudeljs/strudel#6]
Hey Man,

Great job on this so far I really like where it's going. I like the idea of it so much I'd really like to try and help out. I haven't done any Open source contribution before so please help me out there if you'll have me.

Again, this is a great middle ground I also had a few additional ideas and niceties we might be able to add in there. If you're interested let me know!

I look forward to hearing from you!

**Comment by mateuszluczak** [comment]
Hey Paul,

Thanks for the kind words.

Strudel is open for contributions, here you will find detailed guidelines how to contribute - [Contributing Guide](https://github.com/strudeljs/strudel/blob/dev/CONTRIBUTING.md)

Also if you are interested in sharing your ideas and contributing please join [Gitter](https://gitter.im/strudel-js) so we could talk over there instead of here :)

Cheers

**Comment by mateuszluczak** [comment]
I am closing this issue as this is not really an issue - see you on Gitter 😄
